server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/reparaciones-db
    username: postgres
    password: admin
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/