apiVersion: apps/v1
kind: Deployment
metadata:
  name: CATALOGOSR-deployment
  labels:
    app: CATALOGOSR-deployment
spec:
  selector:
    matchLabels:
      app: CATALOGOSR-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: CATALOGOSR-deployment
    spec:
      containers:
        - name: catalogosr
          image: franciscamarquez/catalogosr
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_ORDERS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_ORDERS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_ORDERS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_ORDERS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_ORDERS
